### ISSUE TITLE
Feature Request: Blur Behind between multiple user controls

### ISSUE THREAD

**Issue by ben-hayward** [ConfusedHorse/BlurryControls#19]
Dear Jörg,

Your library currently seems to handle blurring behind windows and dialogs, and can apply blurring to the children of a control. 

I have a project which requires that consists of two user controls, A and B.

- User Control A (UC-A) appears in the background, the most distant component of my window.
- User Control B (UC-B) appears in the foreground, overlaying User Control A. UC-B is partially transparent.

As is common with many UI designs currently (as of Aug. '18), I want it that UC-B causes the all elements behind it to blur (and only the elements behind it), as per the image attached.
![blur](https://user-images.githubusercontent.com/6661246/44980684-7b9ac400-af68-11e8-915f-b8c1f56f75bb.png)

I want to be able to dynamically blur any controls in the background of another control within the same window. 

Is this a feature that you might consider adding to your library? I ask since it seems relevant to the work that you have already done. 

Many thanks in advance!

**Comment by ConfusedHorse** [comment]
What's wrong with the BlurryUserControl? (except that it is very hideous at the moment, but will be refactored soon)

**Comment by ben-hayward** [comment]
My apologies Jörg, yes you are right. From the demo I originally thought it was not possible to include custom elements in the background to be blurred. I was incorrect in thinking this.

In that case, I have another question. Is there any way to make the blurring happen right up to the edges of the user control (a bit like in the image which I posted in my original question)? At the moment, if you increase the blur radius you can see a distinct "fade in" from the edges: 

![temp](https://user-images.githubusercontent.com/6661246/45080878-c85bd780-b0ed-11e8-9dbc-6e2b1f693ec7.jpg)

**Comment by ConfusedHorse** [comment]
This is a problem with the ViewBox and I am already taking care of it. At the moment I do not have much time, due to moving to a new place and work, but I will reference the commit to this post, so you will be informed when it is done. I might also publish a new NuGet version then. :)

**Comment by ben-hayward** [comment]
Awesome, many thanks I look forward to it! Good luck with the move :)

**Comment by ConfusedHorse** [comment]
@ben-hayward I did something which works in the middle of the container control, but not near it's borders. I spent at least 2 hours trying to improve it. I will have another look at it, but probably not in the next couple days. If you have an idea how to do it, let me know. :)

**Comment by ConfusedHorse** [comment]
Still working on it.

**Comment by ConfusedHorse** [comment]
There you go @ben-hayward. I hope this helps. It's not the solution I wanted, but it's an acceptable work around. I added 'Magnification' to prevent the fading on the edge near parent borders.

**Comment by ben-hayward** [comment]
Thank you very much for this Jörg, I shall give it a go!

**Comment by ben-hayward** [comment]
In case it's of any help; I use software such as Adobe Photoshop and After Effects quite regularly. They suffer from the same problem as you when it comes to edge pixels. They get around this by including an option called "Repeat Edge Pixels", meaning the pixels which are inset by _R_ px (where _R_ is the blur radius) are mirrored or duplicated outside of the render zone so that they can be included in the blurring. This negates the need for magnification. I take it you are using magnification to achieve a similar results. The downside is that, well... it's magnified! I hope this helps :)

**Comment by ConfusedHorse** [comment]
Thanks for your suggestion @ben-hayward. Of course I was thinking of something similar, but I wanted to find a solution with the tools already available and not introduce some bitmap magic. I think it would not be performing well anymore when I need to repeat the pixels for every change in position and/or change of the BlurContainer, since a visual change of the BlurContainer is also taken into account (e.g. a gif, or the time in the example project). If I find some spare time, I will fiddle around with a shadow copy of the underlying control with the repeating pixels attached. I will also link it to this issue.
