### ISSUE TITLE
Can you please add an example of a blury shape such as a rectangle?

### ISSUE THREAD

**Issue by PonchoPowers** [ConfusedHorse/BlurryControls#22]

**Comment by ConfusedHorse** [comment]
Umm, like the BlurryUserControl? When you're talking about shapes in a canvas you might want to use WPFs native BlurEffect. See here: [Microsoft Documentation](https://docs.microsoft.com/en-gb/dotnet/api/system.windows.media.effects.blureffect?view=netframework-4.8)

**Comment by ConfusedHorse** [comment]
Note: I will probably not add an example, since I am totally out of touch with WPF. Didn't work with it for over 2 years. But feel free to contribute :)
